version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          docker build -t porterbot-ui:build .
          id=$(docker create porterbot-ui:build)
          docker cp $id:/build/dist .
          docker build -f Dockerfile-runtime -t repo.treescale.com/cecchisandrone/porterbot-ui:latest . 
          docker login repo.treescale.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker push repo.treescale.com/cecchisandrone/porterbot-ui:latest
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: ssh -o StrictHostKeyChecking=no -l pi $PORTERBOT_SSH_HOST -p $PORTERBOT_SSH_PORT "docker pull repo.treescale.com/cecchisandrone/porterbot-ui && docker rm -f porterbot-ui || true &&  docker run --name porterbot-ui -p 80:80 --network porterbot --restart always -d repo.treescale.com/cecchisandrone/porterbot-ui"
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build